import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { DashboardService } from '../campagain/dashboard.service';

@Component({
  selector: 'app-dashboard-socialactive',
  templateUrl: './dashboard-socialactive.component.html',
  styleUrls: ['./dashboard-socialactive.component.css'],

})
export class DashboardSocialactiveComponent implements OnInit{
 
 
  isNameSelectedformDetail:boolean=false;
  isNameSelectedDonationDetail:boolean=false;
  isNameSelectedManageBanner:boolean=false;
  isNameSelectedmyCampaign:boolean=false;
  isNameSelectedAccountDetail=false;
  isNameSelectedPatientDocument=false;
  isNameSelectedStory=false;
  isNameSelectedUpdates=false;
  isNameSelectedplans=false;
  isNameSelectedFund=false;
  isNameSelectedDonor=false;
  isNameSelectedDonation=false;
  isNameSelectedpatientDetail=false;
  isNameSelectedWorkingArea=false;
  textBoxSocialActivist!:FormGroup;
  description=new Array<any>;
  
  constructor(private fb:FormBuilder, private dashboard:DashboardService ){}
  ngOnInit() {
     this.textBoxSocialActivist=this.fb.group({
      description:["",Validators.required]
     })
  }
  onSubmit(){
    this.dashboard.postDashboardSocialActivist(this.textBoxSocialActivist.value).subscribe((data:any)=>{
      console.log(data);
      return data;
    });
    this.dashboard.getDashboardSocialActivist().subscribe((res:any)=>{
      this.description=res;
    });
  }
  onClickWorkingArea(){
    if(this.isNameSelectedWorkingArea!=true){
      this.isNameSelectedWorkingArea=true;
      this.isNameSelectedformDetail=false;
      this.isNameSelectedDonationDetail=false;
      this.isNameSelectedManageBanner=false;
      this.isNameSelectedmyCampaign=false;
      this.isNameSelectedAccountDetail=false;
      this.isNameSelectedPatientDocument=false;
      this.isNameSelectedStory=false;
      this.isNameSelectedUpdates=false;
      this.isNameSelectedplans=false;
      this.isNameSelectedFund=false;
      this.isNameSelectedDonor=false;
      this.isNameSelectedDonation=false;
      this.isNameSelectedpatientDetail=false;
  }
  else{
    this.isNameSelectedWorkingArea=false;
   
   }  
}
  onClickProfileCamp(){
    if(this.isNameSelectedformDetail!=true){
    this.isNameSelectedformDetail=true;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
   }
   else{
    this.isNameSelectedformDetail=false;
   
   }  
 
}
 onClickDonation(){
  if(this.isNameSelectedDonationDetail!=true){
    this.isNameSelectedDonationDetail=true;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedDonationDetail=false;
  }

}
onClickManageBanner(){
  if(this.isNameSelectedManageBanner!=true){
    this.isNameSelectedManageBanner=true;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedManageBanner=false;
  }
 
}
onclickmyCampaign(){
 if(this.isNameSelectedmyCampaign!=true){
  this.isNameSelectedmyCampaign=true;
   this.isNameSelectedManageBanner=false;
   this.isNameSelectedManageBanner=false;
   this.isNameSelectedDonationDetail=false;
   this.isNameSelectedformDetail=false;
   this.isNameSelectedAccountDetail=false;
   this.isNameSelectedPatientDocument=false;
   this.isNameSelectedStory=false;
   this.isNameSelectedUpdates=false;
   this.isNameSelectedplans=false;
   this.isNameSelectedFund=false;
   this.isNameSelectedDonor=false;
   this.isNameSelectedDonation=false;
   this.isNameSelectedpatientDetail=false;
   this.isNameSelectedWorkingArea=false;
 }   
 else{
  this.isNameSelectedmyCampaign=false;
 }
}
onClickAccountDetail(){
  if(this.isNameSelectedAccountDetail!=true){
    this.isNameSelectedAccountDetail=true;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedAccountDetail=false;
  }
}
onClickPatientDetail(){
  if( this.isNameSelectedpatientDetail=true){
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=true;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedPatientDocument=false;
  }
}
onClickPatientDocument(){
  if(this.isNameSelectedPatientDocument!=true){
    this.isNameSelectedPatientDocument=true;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedPatientDocument=false;
  }
}
onClickStory(){
  if(this.isNameSelectedStory!=true){
    this.isNameSelectedStory=true;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedStory=false;
  }
}
onClickupdates(){
  if(this.isNameSelectedUpdates!=true){
    this.isNameSelectedUpdates=true;
    this.isNameSelectedStory=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedUpdates=false;
  }
}
onClickplans(){
  if(this.isNameSelectedplans!=true){
    this.isNameSelectedplans=true;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedplans=false;
  }
}
onClickfunds(){
  if(this.isNameSelectedFund!=true){
    this.isNameSelectedFund=true;
    this.isNameSelectedplans=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
   this.isNameSelectedDonor=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedFund=false;
  }
}
onClickDonor(){
  if(this.isNameSelectedDonor!=true){
    this.isNameSelectedDonor=true;
    this.isNameSelectedFund=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedDonation=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
  else{
    this.isNameSelectedDonor=false;
  }
}
onClickListofDonations(){
  if(this.isNameSelectedDonation!=true){
    this.isNameSelectedDonation=true;
    this.isNameSelectedDonor=false;
    this.isNameSelectedFund=false;
    this.isNameSelectedplans=false;
    this.isNameSelectedUpdates=false;
    this.isNameSelectedStory=false;
    this.isNameSelectedPatientDocument=false;
    this.isNameSelectedAccountDetail=false;
    this.isNameSelectedmyCampaign=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedManageBanner=false;
    this.isNameSelectedDonationDetail=false;
    this.isNameSelectedformDetail=false;
    this.isNameSelectedpatientDetail=false;
    this.isNameSelectedWorkingArea=false;
  }
}
}